GetHTML.py, 33, (<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='amedpost.com%0a', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3571be3588>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),), <traceback object at 0x7f3571be9fc8>)
